### ISSUE TITLE
Unable to compile template in Overleaf

### ISSUE THREAD

**Issue by unlut** [ongun-kanat/itu_graduation_report_template#2]
Unable to compile template in Overleaf

**Comment by gamzeakyol** [comment]
@ongun-kanat Rücktritt!!!

**Comment by ongun-kanat** [comment]
Was? Please provide the error.

**Comment by ongun-kanat** [comment]
I am able to compile. Did you upload the figures properly?

**Comment by gamzeakyol** [comment]
I tried to compile the template in Overleaf v2, it gived many errors. But I can compile it in Overleaf v1 later. Thank you :)

**Comment by ongun-kanat** [comment]
Okay fixed it. Overleaf uses a buggy `babel` version. Shorthand characters in babel-turkish screw up everything.
